"""Report generation service (HTML → PDF + email)."""

import logging
import os
import uuid
from datetime import datetime
from typing import Any

from jinja2 import Template
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.database import AsyncSessionLocal
from app.models.person import Person
from app.models.report import Report

logger = logging.getLogger(__name__)
settings = get_settings()


# =====================================================
# HTML Template for QBR Report
# =====================================================

QBR_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Quarterly Business Review - {{ person_name }}</title>
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #333; }
        h1 { color: #1a5276; border-bottom: 3px solid #2980b9; padding-bottom: 10px; }
        h2 { color: #2c3e50; margin-top: 30px; }
        .metric { display: inline-block; margin: 10px 20px 10px 0; padding: 15px 25px; background: #f0f3f4; border-radius: 8px; text-align: center; }
        .metric .value { font-size: 2em; font-weight: bold; color: #2980b9; }
        .metric .label { font-size: 0.9em; color: #7f8c8d; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #2980b9; color: white; }
        tr:nth-child(even) { background: #f2f4f4; }
        .score-positive { color: #27ae60; }
        .score-negative { color: #e74c3c; }
        .score-neutral { color: #f39c12; }
        .health-score { font-size: 3em; font-weight: bold; text-align: center; padding: 20px;
                        border-radius: 50%; width: 120px; height: 120px; line-height: 120px;
                        margin: 20px auto; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #7f8c8d; font-size: 0.9em; }
    </style>
</head>
<body>
    <h1>📊 Quarterly Business Review</h1>
    <p><strong>Person:</strong> {{ person_name }} | <strong>Generated:</strong> {{ generated_at }}</p>

    <h2>Key Metrics</h2>
    <div>
        <div class="metric"><div class="value">{{ total_meetings }}</div><div class="label">Total Meetings</div></div>
        <div class="metric"><div class="value">{{ health_score }}%</div><div class="label">Health Score</div></div>
        <div class="metric"><div class="value">{{ resolution_rate }}%</div><div class="label">Resolution Rate</div></div>
        <div class="metric"><div class="value">{{ avg_sentiment }}</div><div class="label">Avg Sentiment</div></div>
    </div>

    <h2>Pain Point Summary</h2>
    <table>
        <tr><th>Category</th><th>Count</th><th>Percentage</th></tr>
        {% for pp in pain_points %}
        <tr><td>{{ pp.label }}</td><td>{{ pp.count }}</td><td>{{ pp.percentage }}%</td></tr>
        {% endfor %}
    </table>

    <h2>Sentiment Trend</h2>
    <table>
        <tr><th>Period</th><th>Avg Score</th><th>Meeting Count</th></tr>
        {% for trend in sentiment_trends %}
        <tr>
            <td>{{ trend.period }}</td>
            <td class="{{ 'score-positive' if trend.average_score > 0 else 'score-negative' if trend.average_score < 0 else 'score-neutral' }}">
                {{ trend.average_score }}
            </td>
            <td>{{ trend.meeting_count }}</td>
        </tr>
        {% endfor %}
    </table>

    <h2>Recent Action Items</h2>
    <table>
        <tr><th>Description</th><th>Owner</th><th>Status</th></tr>
        {% for ai in action_items %}
        <tr><td>{{ ai.description }}</td><td>{{ ai.owner }}</td><td>{{ ai.status }}</td></tr>
        {% endfor %}
    </table>

    <div class="footer">
        <p>Generated by AI Call Intelligence System | {{ generated_at }}</p>
    </div>
</body>
</html>
"""


async def generate_qbr_report(
    report_id: str,
    person_id: str,
    include_meetings: int = 5,
    send_email: bool = False,
):
    """
    Generate a QBR report:
    1. Query person trends + recent meetings
    2. Fill Jinja2 HTML template
    3. Convert HTML → PDF
    4. Optionally send email

    This runs as a background task.
    """
    async with AsyncSessionLocal() as db:
        try:
            from app.services.analytics_service import get_person_analytics

            report_uuid = uuid.UUID(report_id)

            # Get analytics data
            analytics = await get_person_analytics(
                person_id=person_id,
                months=3,
                db=db,
            )

            # Fill template
            template = Template(QBR_HTML_TEMPLATE)
            html_content = template.render(
                person_name=analytics["person_name"],
                generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
                total_meetings=analytics["total_meetings"],
                health_score=analytics["health_score"],
                resolution_rate=analytics["resolution_rate"],
                avg_sentiment=analytics["sentiment_trends"][-1]["average_score"] if analytics["sentiment_trends"] else 0,
                pain_points=analytics["pain_point_frequencies"],
                sentiment_trends=analytics["sentiment_trends"],
                action_items=analytics["recent_action_items"],
            )

            # Save PDF
            pdf_dir = os.path.join(settings.STORAGE_PATH, "reports")
            os.makedirs(pdf_dir, exist_ok=True)
            pdf_path = os.path.join(pdf_dir, f"qbr_{report_id}.pdf")

            try:
                # WeasyPrint HTML → PDF conversion
                from weasyprint import HTML
                HTML(string=html_content).write_pdf(pdf_path)
                logger.info(f"PDF generated: {pdf_path}")
            except ImportError:
                # Fallback: save HTML only
                html_path = os.path.join(pdf_dir, f"qbr_{report_id}.html")
                with open(html_path, "w") as f:
                    f.write(html_content)
                pdf_path = html_path
                logger.warning("WeasyPrint not installed, saved as HTML only")

            # Update report record
            report_result = await db.execute(
                select(Report).where(Report.id == report_uuid)
            )
            report = report_result.scalar_one()
            report.content_html = html_content
            report.pdf_path = pdf_path
            report.status = "completed"

            # Send email if requested
            if send_email:
                await _send_report_email(
                    person_name=analytics["person_name"],
                    pdf_path=pdf_path,
                    db=db,
                )
                report.status = "sent"

            await db.commit()
            logger.info(f"QBR report {report_id} completed successfully")

        except Exception as e:
            logger.error(f"QBR report generation failed: {e}")
            report_result = await db.execute(
                select(Report).where(Report.id == uuid.UUID(report_id))
            )
            report = report_result.scalar_one_or_none()
            if report:
                report.status = "failed"
                await db.commit()
            raise


async def _send_report_email(person_name: str, pdf_path: str, db: AsyncSession):
    """
    Send report via email.
    Stub: logs the action. Replace with actual SMTP sending.
    """
    # Production:
    # import smtplib
    # from email.mime.multipart import MIMEMultipart
    # from email.mime.application import MIMEApplication
    #
    # msg = MIMEMultipart()
    # msg["Subject"] = f"QBR Report - {person_name}"
    # msg["From"] = settings.SMTP_USER
    # msg["To"] = recipient_email
    #
    # with open(pdf_path, "rb") as f:
    #     attachment = MIMEApplication(f.read(), _subtype="pdf")
    #     attachment.add_header("Content-Disposition", "attachment", filename=f"QBR_{person_name}.pdf")
    #     msg.attach(attachment)
    #
    # with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
    #     server.starttls()
    #     server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
    #     server.send_message(msg)

    logger.info(f"[STUB] Would send QBR report email for {person_name} (PDF: {pdf_path})")
